spring.datasource.url=jdbc:mysql://localhost:3306/moodfilm?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#googleOAuth
google.client-id=${GOOGLE_CLIENT_ID:1015555906160-nk052b4objv9a1rnnvsgn6iouv1i66hr.apps.googleusercontent.com}

#correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=moodfilm.app@gmail.com
spring.mail.password=ujvo vyxv utvx smrh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#TMDB
tmdb.api.key=${TMDB_API_KEY:ef7e2eea6a70b4a7b8bb8c73cdf9d549}

#JWT
jwt.secret=${JWT_SECRET:moodfilm_clave_secreta_larga_moodfilm_clave_secreta_larga}