spring.application.name=apiMoodFilm

spring.datasource.url=jdbc:mysql://localhost:3306/moodfilm?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Para conectar con la api tmdb de peliculas:
tmdb.api.key=ef7e2eea6a70b4a7b8bb8c73cdf9d549
tmdb.base.url=https://api.themoviedb.org/3